#http://localhost/service-provider/provider/test

server:
  port: 80
  servlet:
    context-path: /
spring:
  application:
    name: spring-cloud-gateway-demo
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   #开启Eureka服务发现
          lower-case-service-id: true
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server.com:9000/eureka/,http://eureka-server1.com:9001/eureka/
  instance:
    prefer-ip-address: true


