#http://localhost/service-provider/provider/test

server:
  port: 80
  servlet:
    context-path: /
spring:
  application:
    name: spring-cloud-gateway-demo
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
          lower-case-service-id: true
      routes:
        - id: provider1 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:9010          #匹配后提供服务的路由地址
          uri: lb://eureka-provider #匹配后提供服务的路由地址
          predicates:
            - Path=/provider/**         # 断言，路径相匹配的进行路由
          metadata:
            connect-timeout: 10
            #单位毫秒
            response-timeout: 10000
eureka:
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka-server.com:9000/eureka/,http://eureka-server1.com:9001/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    root: debug


